import "./globals.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";

const hagrid = localFont({
  src: "../../public/fonts/Hagrid.woff",
  variable: "--font-hagrid",
});

const fagun = localFont({
  src: "../../public/fonts/Fagun.woff",
  variable: "--font-fagun",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${hagrid.variable} ${geistSans.variable} ${geistMono.variable} ${fagun.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
