"use client";

import "./globals.css";

import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "@fontsource-variable/manrope/wght.css";
import "@fontsource-variable/space-grotesk/wght.css";
import "@fontsource-variable/inter/wght.css";
import localFont from "next/font/local";

import { useRef } from "react";

import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
import { ScrollSmoother } from "gsap/dist/ScrollSmoother";
import { useGSAP } from "@gsap/react";
import { NavigationMenuHome2 } from "@/components/bar/navmenu2";

import NavbarLayout from "@/components/bar/navbarLayout";
import BottomNav from "@/components/bar/bottomNav";

const hagrid = localFont({
  src: "../fonts/HagridTrial-Regular.woff2",
  variable: "--font-hagrid",
  weight: "100 900",
});

const fagun = localFont({
  src: "../fonts/FagunTrial-Medium.woff2",
  variable: "--font-fagun",
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const smootherRef = useRef<ScrollSmoother | null>(null);

  useGSAP(() => {
    gsap.registerPlugin(ScrollTrigger, ScrollSmoother);

    smootherRef.current = ScrollSmoother.create({
      wrapper: "#smooth-wrapper",
      content: "#smooth-content",
      smooth: 1.5,
      effects: true,
    });

    return () => {
      smootherRef.current?.kill();
    };
  }, []);
  return (
    <html lang="en">
      <body className={`${hagrid.variable} ${fagun.variable} antialiased`}>
        <NavbarLayout />
        <BottomNav />
        <div id="smooth-wrapper">
          <div id="smooth-content">{children}</div>
        </div>
      </body>
    </html>
  );
}
